name = "JLD"
uuid = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
version = "0.12.6"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
H5Zblosc = "c8ec2601-a99c-407f-b158-e79c03c2f5f7"

[compat]
FileIO = "1"
HDF5 = "0.16"
H5Zblosc = "0.1"
Compat = "3.40"
julia = "1.3"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "LinearAlgebra", "Random", "Profile", "Test"]
